#!/usr/bin/env python
#-*- coding:utf-8 -*-
#author ren
#QQ:315420700

import commands
import sys
import json

py_name=sys.argv[0]
server_name=sys.argv[1]
command1 = "netstat -lntp|egrep -v 'tcp6|udp6' |tail -n +3|awk -F '[ :/]'+ '{print $5,$9,$10}'|sort -k3|uniq"

def getComStr(cmd):
    try:
        stat,proStr = commands.getstatusoutput(cmd)
        proList = proStr.split("\n")
    except:
        print "command %s execute failed, exit" %(cmd)
    return proList

def filterList(cmd,server):
    Services_Str = getComStr(cmd)
    Services_List = []
    Services_dict = {}
    for i in Services_Str:
        val = i.split()
        if val[2] == server:
            Service_dict={
             "#{PORT}":val[0],
             "#{PID}":val[1],
             "#{SERVICE}":val[2],
            }
            Services_List.append(Service_dict)
    return Services_List

def main():
    Services_List=filterList(command1,server_name)
    #print Services_List
    
    Services_Json=json.dumps({"data":Services_List},sort_keys=True,indent=4)
    print Services_Json

if __name__=="__main__":
   main()
