#!/bin/bash
#This script is used to get mongodb server status

case $# in
  1)
    output=$(/bin/echo "db.serverStatus().$1" |/usr/local/mongodb-3.0.6/bin/mongo 127.0.0.1:20000 --quiet)
    ;;
  2)
    output=$(/bin/echo "db.serverStatus().$1.$2" |/usr/local/mongodb-3.0.6/bin/mongo 127.0.0.1:20000 --quiet)
    ;;
  3)
    output=$(/bin/echo "db.serverStatus().$1.$2.$3" |/usr/local/mongodb-3.0.6/bin/mongo 127.0.0.1:20000 --quiet)
    ;;
#  4)
#    output=$(/bin/echo "db.serverStatus().$1.$2.$3" |/usr/local/mongodb-3.0.6/bin/mongo 127.0.0.1\:$4 --quiet)
#    ;;
  *)
    ;;
esac
if [[ "$output" =~ "NumberLong" ]];then
  echo $output|sed -n 's/NumberLong(//p'|sed -n 's/)//p'
else
  echo $output
fi
