#!/usr/bin/env python
# _*_coding: utf-8_*_
#encoding=utf-8
import os
import json
CPU = []
cpunum = os.popen('cat /proc/cpuinfo |grep processor|wc -l')
#cpunum_tmp = range(0,int(cpunum.read()))
#for i in cpunum_tmp:
for i in range(0,int(cpunum.read())):
  CPU+=[{"{#CPU}":i}]
print json.dumps({'data':CPU},sort_keys=True,indent=4)
